// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddDescription(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['appshell']['App']['AddDescription'](arg1, arg2, arg3, arg4, arg5);
}

export function AddFolder(arg1) {
  return window['go']['appshell']['App']['AddFolder'](arg1);
}

export function CancelLocalVaultImport() {
  return window['go']['appshell']['App']['CancelLocalVaultImport']();
}

export function ChangeMasterPassword(arg1, arg2) {
  return window['go']['appshell']['App']['ChangeMasterPassword'](arg1, arg2);
}

export function ConfirmLocalVaultImport(arg1) {
  return window['go']['appshell']['App']['ConfirmLocalVaultImport'](arg1);
}

export function CopyToClipboard(arg1) {
  return window['go']['appshell']['App']['CopyToClipboard'](arg1);
}

export function CreateProfile(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['appshell']['App']['CreateProfile'](arg1, arg2, arg3, arg4, arg5);
}

export function DeleteDescription(arg1) {
  return window['go']['appshell']['App']['DeleteDescription'](arg1);
}

export function DeleteFolder(arg1) {
  return window['go']['appshell']['App']['DeleteFolder'](arg1);
}

export function DeleteProfile(arg1) {
  return window['go']['appshell']['App']['DeleteProfile'](arg1);
}

export function ExportLocalVaultToFile(arg1) {
  return window['go']['appshell']['App']['ExportLocalVaultToFile'](arg1);
}

export function ExportProfileJSON(arg1) {
  return window['go']['appshell']['App']['ExportProfileJSON'](arg1);
}

export function ExportProfileToFile(arg1) {
  return window['go']['appshell']['App']['ExportProfileToFile'](arg1);
}

export function GetAutoLockMinutes() {
  return window['go']['appshell']['App']['GetAutoLockMinutes']();
}

export function GetSession() {
  return window['go']['appshell']['App']['GetSession']();
}

export function GetVault() {
  return window['go']['appshell']['App']['GetVault']();
}

export function GitVersion() {
  return window['go']['appshell']['App']['GitVersion']();
}

export function ImportProfileFromFile() {
  return window['go']['appshell']['App']['ImportProfileFromFile']();
}

export function ImportProfileJSON(arg1) {
  return window['go']['appshell']['App']['ImportProfileJSON'](arg1);
}

export function ListProfiles() {
  return window['go']['appshell']['App']['ListProfiles']();
}

export function Login(arg1, arg2) {
  return window['go']['appshell']['App']['Login'](arg1, arg2);
}

export function Logout() {
  return window['go']['appshell']['App']['Logout']();
}

export function PickLocalVaultImport() {
  return window['go']['appshell']['App']['PickLocalVaultImport']();
}

export function Refresh() {
  return window['go']['appshell']['App']['Refresh']();
}

export function RenameFolder(arg1, arg2) {
  return window['go']['appshell']['App']['RenameFolder'](arg1, arg2);
}

export function RenameProfile(arg1, arg2) {
  return window['go']['appshell']['App']['RenameProfile'](arg1, arg2);
}

export function RetryPush() {
  return window['go']['appshell']['App']['RetryPush']();
}

export function Save() {
  return window['go']['appshell']['App']['Save']();
}

export function SaveProfileRemote(arg1, arg2, arg3, arg4) {
  return window['go']['appshell']['App']['SaveProfileRemote'](arg1, arg2, arg3, arg4);
}

export function SetAutoLockMinutes(arg1) {
  return window['go']['appshell']['App']['SetAutoLockMinutes'](arg1);
}

export function SetUILocale(arg1) {
  return window['go']['appshell']['App']['SetUILocale'](arg1);
}

export function UpdateDescriptionKey(arg1, arg2) {
  return window['go']['appshell']['App']['UpdateDescriptionKey'](arg1, arg2);
}

export function UpdateDescriptionPassword(arg1, arg2) {
  return window['go']['appshell']['App']['UpdateDescriptionPassword'](arg1, arg2);
}

export function UpdateDescriptionTitle(arg1, arg2) {
  return window['go']['appshell']['App']['UpdateDescriptionTitle'](arg1, arg2);
}

export function UpdateDescriptionValue(arg1, arg2) {
  return window['go']['appshell']['App']['UpdateDescriptionValue'](arg1, arg2);
}

export function UpdateProfilePAT(arg1, arg2) {
  return window['go']['appshell']['App']['UpdateProfilePAT'](arg1, arg2);
}
