// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {appshell} from '../models';
import {vaultcore} from '../models';

export function AddDescription(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;

export function AddFolder(arg1:string):Promise<void>;

export function CancelLocalVaultImport():Promise<void>;

export function ChangeMasterPassword(arg1:string,arg2:string):Promise<void>;

export function ConfirmLocalVaultImport(arg1:string):Promise<appshell.ProfileDTO>;

export function CopyToClipboard(arg1:string):Promise<void>;

export function CreateProfile(arg1:string,arg2:string,arg3:string,arg4:string,arg5:boolean):Promise<appshell.ProfileDTO>;

export function DeleteDescription(arg1:string):Promise<void>;

export function DeleteFolder(arg1:string):Promise<void>;

export function DeleteProfile(arg1:string):Promise<void>;

export function ExportLocalVaultToFile(arg1:string):Promise<void>;

export function ExportProfileJSON(arg1:string):Promise<string>;

export function ExportProfileToFile(arg1:string):Promise<void>;

export function GetAutoLockMinutes():Promise<number>;

export function GetSession():Promise<appshell.SessionDTO>;

export function GetVault():Promise<vaultcore.Vault>;

export function GitVersion():Promise<string>;

export function ImportProfileFromFile():Promise<appshell.ProfileDTO>;

export function ImportProfileJSON(arg1:string):Promise<appshell.ProfileDTO>;

export function ListProfiles():Promise<Array<appshell.ProfileDTO>>;

export function Login(arg1:string,arg2:string):Promise<void>;

export function Logout():Promise<void>;

export function PickLocalVaultImport():Promise<appshell.LocalVaultImportPickDTO>;

export function Refresh():Promise<void>;

export function RenameFolder(arg1:string,arg2:string):Promise<void>;

export function RenameProfile(arg1:string,arg2:string):Promise<void>;

export function RetryPush():Promise<void>;

export function Save():Promise<void>;

export function SaveProfileRemote(arg1:string,arg2:string,arg3:string,arg4:string):Promise<appshell.RemoteSaveResult>;

export function SetAutoLockMinutes(arg1:number):Promise<void>;

export function SetUILocale(arg1:string):Promise<void>;

export function UpdateDescriptionKey(arg1:string,arg2:string):Promise<void>;

export function UpdateDescriptionPassword(arg1:string,arg2:string):Promise<void>;

export function UpdateDescriptionTitle(arg1:string,arg2:string):Promise<void>;

export function UpdateDescriptionValue(arg1:string,arg2:string):Promise<void>;

export function UpdateProfilePAT(arg1:string,arg2:string):Promise<void>;
